# Environment Variables Example for NestJS

# General Configuration
PORT: <PORT value>
NODE_ENV: <"development | test | production">

# Redis Configuration
REDIS_CONNECTION_URI: "<REDIS_CONNECTION_URI value>"

# Database Configuration
DEV_DB_URI: "<DEV_DB_URI value>"
STAG_DB_URI: "<STAG_DB_URI value>"
PROD_DB_URI: "<PROD_DB_URI value>"
ALTER_TABLES: <ALTER_TABLES value>

# Cryptography Configuration
ENCRYPTION_KEY: <ENCRYPTION_KEY value>
HASH_SALT: <HASH_SALT value>

# JWT Configuration
JWT_SECRET: "<JWT_SECRET value>"
JWT_REFRESH_EXP: <JWT_REFRESH_EXP value>
JWT_ACCESS_EXP: <JWT_ACCESS_EXP value>
JWT_EXPIRATION_THRESHOLD: <JWT_EXPIRATION_THRESHOLD value>
SIGNOUT_EXP: <SIGNOUT_EXP value>

# Mail Configuration
GMAIL_CLIENT_ID: "<GMAIL_CLIENT_ID value>"
GMAIL_REDIRECT_SECRET: "<GMAIL_REDIRECT_SECRET value>"
GMAIL_REDIRECT_URI: "<GMAIL_REDIRECT_URI value>"
GMAIL_REFRESH_TOKEN: "<GMAIL_REFRESH_TOKEN value>"
GMAIL_CLIENT_FROM: "<GMAIL_CLIENT_FROM value>"
FRONTEND_URL: "<FRONTEND_URL value>"

# Super Admin Configuration
SUPER_ADMIN_EMAIL: "<SUPER_ADMIN_EMAIL value>"
SUPER_ADMIN_FIRSTNAME: "<SUPER_ADMIN_FIRSTNAME value>"
SUPER_ADMIN_LASTNAME: "<SUPER_ADMIN_LASTNAME value>"
SUPER_ADMIN_PASSWORD: "<SUPER_ADMIN_PASSWORD value>"
