import { ConfigService } from "@nestjs/config";

export const jwtConstants = () => {
  const s = new ConfigService();
  return {
    secret: s.get("JWT_SECRET")
  };
};

export enum AuthErrors {
  USERNAME_TAKEN = "USERNAME_TAKEN",
  INVALID_TOKEN = "INVALID_TOKEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  SAME_PASSWORD = "SAME_PASSWORD",
  INVALID_HEADERS = "INVALID_HEADERS",
  UNKNOWN_USER = "UNKNOWN_USER",
  UNKNOWN_MEMBER = "UNKNOWN_MEMBER",
  ALREADY_REGISTERED = "ALREADY_REGISTERED",
  PASS_DOESNT_MATCH = "PASS_DOESNT_MATCH",
  SERVER_ERROR = "SERVER_ERROR",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  IP_BLOCKED = "IP_BLOCKED",
  UNEXPECTED_ERROR = "UNEXPECTED_ERROR",
  PASSWORD_REUSE_NOT_ALLOWED = "PASSWORD_REUSE_NOT_ALLOWED",
  PASSWORD_RESET_EXPIRED = "PASSWORD_RESET_EXPIRED",
  UNAUTHORIZED_DEVICE = "UNAUTHORIZED_DEVICE",
  INVALID_SECURITY_KEY = "INVALID_SECURITY_KEY",
  INVALID_ORIGIN = "INVALID_ORIGIN",
  LIMIT_EXCEEDED = "LIMIT_EXCEEDED",
  SESSION_EXIPIRED = "SESSION_EXPIRED",
  UNAUTHORIZED_REQUEST = "UNAUTHORIZED_REQUEST",
  INVALID_INPUT = "INVALID_INPUT"
}
